####################
# Assignment 4
####################

Overall: 20/51
====================
Test Case: [function=multiply_factors_test_1]	[0/2]
	MF Test 1 ....
multiply_factors_test_1: 
A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/A4-Final/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 313, in multiply_factors_test_1\n    values = (factor.get_value([\'smoker\']), factor.get_value([\'non-smoker\']))\nAttributeError: \'NoneType\' object has no attribute \'get_value\'\n'
====================
Test Case: [function=multiply_factors_test_2]	[0/2]
	A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/A4-Final/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 352, in multiply_factors_test_2\n    value = factor.get_value([val1, val2])\nAttributeError: \'NoneType\' object has no attribute \'get_value\'\n'
MF Test 2 ....
multiply_factors_test_2: 
====================
Test Case: [function=multiply_factors_test_3]	[0/2]
	multiply_factors_test_3: 
A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/A4-Final/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 398, in multiply_factors_test_3\n    value = factor.get_value([val1, val2, val3])\nAttributeError: \'NoneType\' object has no attribute \'get_value\'\n'
MF Test 3 ....
====================
Test Case: [function=norm_test_1]	[1/1]
	{'passed.', '[0, 1, 2, 3, 4] when normalized to [0.0, 0.1, 0.2, 0.3, 0.4] sum to 1.0', 'Normalization test 1 ....'}
====================
Test Case: [function=norm_test_2]	[1/1]
	{'[0, -1, -2, -3, -4] when normalized to [-0.0, 0.1, 0.2, 0.3, 0.4] sum to 1.0', 'passed.', 'Normalization test 2 ....'}
====================
Test Case: [function=norm_test_3]	[1/1]
	{'Normalization test 3 ....', 'passed.', '[4, 3, 2, 1, 0, -1, -2, -3, -4] when normalized to [0, 0, 0, 0, 0, 0, 0, 0, 0] sum to 0'}
====================
Test Case: [function=old_VE_tests]	[0/8]
	OVE Test 1 ....
OVE Test 3 ....
A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/A4-Final/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 664, in old_VE_tests\n    if probs[0] == 1 and probs[1] == 0:\nTypeError: \'NoneType\' object is not subscriptable\n'
OVE Test 2 ....
A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/A4-Final/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 768, in old_VE_tests\n    if abs(probs1[0] - 0.15265998457979954) < 0.0001 and abs(probs1[1] - 0.8473400154202004) < 0.0001 and abs(probs2[0] - 0.01336753983256819) < 0.0001 and abs(probs2[1] - 0.9866324601674318) < 0.0001:\nTypeError: \'NoneType\' object is not subscriptable\n'
A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/A4-Final/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 748, in old_VE_tests\n    if probs3[0] == 0.0 and probs3[1] == 1.0 and probs4[0] == 0.0 and probs4[1] == 1.0:\nTypeError: \'NoneType\' object is not subscriptable\n'
Test 8 ....
A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/A4-Final/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 684, in old_VE_tests\n    if abs(probs[0] - 0.68) < 0.0001 and abs(probs[1] - 0.32) < 0.0001:\nTypeError: \'NoneType\' object is not subscriptable\n'
A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/A4-Final/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 785, in old_VE_tests\n    if abs(probs[0] - 0.04950000000000001) < .0001 and abs(probs[1] - 0.9505) < .0001:\nTypeError: \'NoneType\' object is not subscriptable\n'
OVE Test 5 ....
old_VE_tests: 
A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/A4-Final/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 705, in old_VE_tests\n    if probs1[0] == 0.5 and probs1[1] == 0.5 and probs2[0] == 0.0 and probs2[1] == 1.0:\nTypeError: \'NoneType\' object is not subscriptable\n'
OVE Test 6 ....
A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/A4-Final/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 801, in old_VE_tests\n    if abs(probs[0] - 0.1) < 0.0001 and abs(probs[1] - 0.9) < 0.0001:\nTypeError: \'NoneType\' object is not subscriptable\n'
OVE Test 4 ....
A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/A4-Final/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 727, in old_VE_tests\n    if probs1[0] == 0.5 and probs1[1] == 0.5 and probs2[0] == 0.5 and probs2[1] == 0.5:\nTypeError: \'NoneType\' object is not subscriptable\n'
OVE Test 7 ....
====================
Test Case: [function=old_multiply_factors_tests]	[0/3]
	OMF Test 3 ....
OMF Test 1 ....
A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/A4-Final/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 841, in old_multiply_factors_tests\n    values = (factor.get_value([\'e\']), factor.get_value([\'-e\']))\nAttributeError: \'NoneType\' object has no attribute \'get_value\'\n'
old_multiply_factors_tests: 
OMF Test 2 ....
A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/A4-Final/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 891, in old_multiply_factors_tests\n    value = factor.get_value([e_val, b_val, s_val])\nAttributeError: \'NoneType\' object has no attribute \'get_value\'\n'
A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/A4-Final/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 863, in old_multiply_factors_tests\n    value = factor.get_value([e_val, b_val])\nAttributeError: \'NoneType\' object has no attribute \'get_value\'\n'
====================
Test Case: [function=old_restrict_factor_tests]	[3/3]
	P(S=-s|E=-e,B=b) = 0.2
passed.
P(E=e) = 0.1
P(G=-g|S=s) = 1
ORF Test 1 ....
ORF Test 2 ....
ORF Test 3 ....
old_restrict_factor_tests: 
====================
Test Case: [function=old_sum_out_variable_tests]	[2/2]
	old_sum_out_variable_tests: 
passed.
P(S = s | B = b) = 1.7000000000000002 P(S = s | B = -b) = 0.2 P(S = -s | B = b) = 0.30000000000000004 P(S = -s | B = -b) = 1.8
sum_e P(e) = 1.0
OSOV Test 1 ....
OSOV Test 2 ....
====================
Test Case: [function=restrict_factor_test_1]	[2/2]
	restrict_factor_test_1: 
passed.
P(VisitAsia=visit) = 0.01

Restrict Factor Tests
RF Test 1 ....
====================
Test Case: [function=restrict_factor_test_2]	[2/2]
	P(Bronchitis=absent|Smoking=non-smoker) = 0.7
passed.
restrict_factor_test_2: 
RF Test 2 ....
====================
Test Case: [function=restrict_factor_test_3]	[2/2]
	passed.
RF Test 3 ....
restrict_factor_test_3: 
P(Dyspnea=absent|TBorCA=true,Bronchitis=present) = 0.1
====================
Test Case: [function=sum_out_variable_test_1]	[2/2]
	SOV Test 1 ....
passed.
sum_out_variable_test_1: 
sum P(VisitAsia) = 1.0
====================
Test Case: [function=sum_out_variable_test_2]	[2/2]
	passed.
P(Cancer = present) = 0.11 P(Cancer = absent) = 1.8900000000000001 
SOV Test 2 ....
sum_out_variable_test_2: 
====================
Test Case: [function=sum_out_variable_test_3]	[2/2]
	SOV Test 3 ....
passed.
sum_out_variable_test_3: 
P(TBorC = true) = 3.0 P(TBorC = false) = 1 
====================
Test Case: [function=ve_test_1]	[0/2]
	VE Test 1 ....
A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/A4-Final/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 85, in ve_test_1\n    if abs(probs[0] - 0.6) < 0.001 and abs(probs[1] - 0.4) < 0.001:\nTypeError: \'NoneType\' object is not subscriptable\n'
ve_test_1: 
====================
Test Case: [function=ve_test_2]	[0/2]
	ve_test_2: 
VE Test 2 ....
A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/A4-Final/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 118, in ve_test_2\n    if abs(probs[0] - 0.789) < 0.001 and probs[1] == 0.21:\nTypeError: \'NoneType\' object is not subscriptable\n'
====================
Test Case: [function=ve_test_3]	[0/2]
	ve_test_3: 
VE Test 3 ....
A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/A4-Final/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 150, in ve_test_3\n    if abs(probs[0] - 0.8106077620781144) < 0.001 and abs(probs[1] - 0.1893922379218856) < 0.001:\nTypeError: \'NoneType\' object is not subscriptable\n'
====================
Test Case: [function=ve_test_4]	[0/2]
	A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/A4-Final/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 184, in ve_test_4\n    if abs(probs[0] - 0.145) < 0.001 and abs(probs[1] - 0.855) < 0.001:\nTypeError: \'NoneType\' object is not subscriptable\n'
ve_test_4: 
VE Test 4 ....
====================
Test Case: [function=ve_test_5]	[0/2]
	ve_test_5: 
VE Test 5 ....
A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/A4-Final/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 218, in ve_test_5\n    if abs(probs[0] - 0.5760396859045477) < 0.001 and abs(probs[1] - 0.4239603140954523) < 0.001:\nTypeError: \'NoneType\' object is not subscriptable\n'
====================
Test Case: [function=ve_test_6]	[0/2]
	VE Test 6 ....
ve_test_6: 
A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/A4-Final/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 248, in ve_test_6\n    if abs(probs[0] - 0.055) < 0.001 and abs(probs[1] - 0.945) < 0.001:\nTypeError: \'NoneType\' object is not subscriptable\n'
====================
Test Case: [function=ve_test_7]	[0/2]
	A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/A4-Final/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 284, in ve_test_7\n    if abs(probs1[0] - 0.6339) < 0.0001 and abs(probs1[1] - 0.366) < 0.0001 and abs(probs2[0] - 0.3964) < 0.0001 and abs(probs2[1] - 0.60357) < 0.0001:\nTypeError: \'NoneType\' object is not subscriptable\n'
VE Test 7 ....
ve_test_7: 