####################
# Assignment 4
####################

Overall: 21/32
====================
Test Case: [function=multiply_factors_test_1]	[1/1]
	P(smoker) = 0.5 P(non-smoker) = 0.5
MF Test 1 ....
multiply_factors_test_1: 
passed.
====================
Test Case: [function=multiply_factors_test_2]	[1/1]
	MF Test 2 ....
P(visit,smoker) = 0.005 P(no-visit,smoker) = 0.005 P(visit,non-smoker) = 0.495 P(no-visit,non-smoker) = 0.495
multiply_factors_test_2: 
passed.
====================
Test Case: [function=multiply_factors_test_3]	[1/1]
	MF Test 3 ....
multiply_factors_test_3: 
passed.
F1 x F5 = [0.006, 0.003, 0.004, 0.006999999999999999, 0.594, 0.297, 0.396, 0.693]
====================
Test Case: [function=old_VE_tests]	[8/8]
	P(g|s,w) = 0.5 P(-g|s,w) = 0.5 P(g|s,-w) = 0.5 P(-g|s,-w) = 0.5
Test 8 ....
OVE Test 4 ....
OVE Test 1 ....
OVE Test 5 ....
OVE Test 7 ....
P(g) = 0.04950000000000001 P(-g) = 0.9505
P(g|s) = 0.5 P(-g|s) = 0.5 P(g|-s) = 0.0 P(-g|-s) = 1.0
P(g|w) = 0.15265998457979954 P(-g|w) = 0.8473400154202004 P(g|-w) = 0.01336753983256819 P(-g|-w) = 0.9866324601674318
P(s|g) = 1.0 P(-s|g) = 0.0
OVE Test 3 ....
P(g|-s,w) = 0.0 P(-g|-s,w) = 1.0 P(g|-s,-w) = 0.0 P(-g|-s,-w) = 1.0
passed.
P(e) = 0.1 P(-e) = 0.9
OVE Test 2 ....
OVE Test 6 ....
old_VE_tests: 
P(w|b,-e) = 0.68 P(-w|b,-e) = 0.32
====================
Test Case: [function=old_multiply_factors_tests]	[3/3]
	P(e,s,b) = 0.09000000000000001 P(-e,s,b) = 0.010000000000000002 P(e,-s,-b) = 0.020000000000000004 P(-e,s,-b) = 0.08000000000000002
old_multiply_factors_tests: 
OMF Test 1 ....
P(e) = 0.1 P(-e) = 0.9
passed.
OMF Test 2 ....
OMF Test 3 ....
P(e,b) = 0.010000000000000002 P(-e,b) = 0.09000000000000001 P(e,-b) = 0.09000000000000001 P(-e,-b) = 0.81
====================
Test Case: [function=old_restrict_factor_tests]	[2/3]
	P(S=-s|E=-e,B=b) = 0.2
old_restrict_factor_tests: 
ORF Test 3 ....
ORF Test 2 ....
ORF Test 1 ....
P(E=e) = 0.1
P(G=-g|S=s) = 0
passed.
failed.
====================
Test Case: [function=old_sum_out_variable_tests]	[2/2]
	P(S = s | B = b) = 1.7000000000000002 P(S = s | B = -b) = 0.2 P(S = -s | B = b) = 0.30000000000000004 P(S = -s | B = -b) = 1.8
OSOV Test 2 ....
OSOV Test 1 ....
old_sum_out_variable_tests: 
sum_e P(e) = 1
passed.
====================
Test Case: [function=restrict_factor_test_1]	[1/1]
	RF Test 1 ....
restrict_factor_test_1: 
P(VisitAsia=visit) = 0.01
passed.

Restrict Factor Tests
====================
Test Case: [function=restrict_factor_test_2]	[0/1]
	restrict_factor_test_2: 
P(Bronchitis=absent|Smoking=non-smoker) = 0
failed.
RF Test 2 ....
====================
Test Case: [function=restrict_factor_test_3]	[0/1]
	restrict_factor_test_3: 
A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 464, in restrict_factor_test_3\n    factor = stu_solution.restrict_factor(F7, Dyspnea, \'absent\')\n  File "students//yesmukha/A4/bnetbase.py", line 423, in restrict_factor\n    Restrict.add_values(values)\n  File "students//yesmukha/A4/bnetbase.py", line 170, in add_values\n    index = index * v.domain_size() + v.value_index(t[0])\n  File "students//yesmukha/A4/bnetbase.py", line 68, in value_index\n    return self.dom.index(value)\nValueError: \'present\' is not in list\n'
RF Test 3 ....
====================
Test Case: [function=sum_out_variable_test_1]	[1/1]
	sum_out_variable_test_1: 
SOV Test 1 ....
passed.
sum P(VisitAsia) = 1
====================
Test Case: [function=sum_out_variable_test_2]	[1/1]
	sum_out_variable_test_2: 
P(Cancer = present) = 0.11 P(Cancer = absent) = 1.8900000000000001 
passed.
SOV Test 2 ....
====================
Test Case: [function=sum_out_variable_test_3]	[0/1]
	Got TIMEOUT
sum_out_variable_test_3: 
SOV Test 3 ....
====================
Test Case: [function=ve_test_1]	[0/1]
	VE Test 1 ....
Got TIMEOUT
ve_test_1: 
====================
Test Case: [function=ve_test_2]	[0/1]
	ve_test_2: 
A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 63, in ve_test_2\n    probs = stu_solution.VE(Asia, Dyspnea, [Tuberculosis])\n  File "students//yesmukha/A4/bnetbase.py", line 612, in VE\n    new_factor = sum_out_variable(multiply_factors(bucket), var)\n  File "students//yesmukha/A4/bnetbase.py", line 362, in multiply_factors\n    value = value * f.get_value(n)\n  File "students//yesmukha/A4/bnetbase.py", line 227, in get_value\n    index = index * v.domain_size() + v.value_index(variable_values[0])\n  File "students//yesmukha/A4/bnetbase.py", line 68, in value_index\n    return self.dom.index(value)\nValueError: \'absent\' is not in list\n'
VE Test 2 ....
====================
Test Case: [function=ve_test_3]	[0/1]
	ve_test_3: 
VE Test 3 ....
A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 95, in ve_test_3\n    probs = stu_solution.VE(Asia, Dyspnea, [TBorCA])\n  File "students//yesmukha/A4/bnetbase.py", line 612, in VE\n    new_factor = sum_out_variable(multiply_factors(bucket), var)\n  File "students//yesmukha/A4/bnetbase.py", line 362, in multiply_factors\n    value = value * f.get_value(n)\n  File "students//yesmukha/A4/bnetbase.py", line 227, in get_value\n    index = index * v.domain_size() + v.value_index(variable_values[0])\n  File "students//yesmukha/A4/bnetbase.py", line 68, in value_index\n    return self.dom.index(value)\nValueError: \'absent\' is not in list\n'
====================
Test Case: [function=ve_test_4]	[0/1]
	ve_test_4: 
VE Test 4 ....
Got TIMEOUT
====================
Test Case: [function=ve_test_5]	[0/1]
	ve_test_5: 
A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 163, in ve_test_5\n    probs = stu_solution.VE(Asia, TBorCA, [Xray])\n  File "students//yesmukha/A4/bnetbase.py", line 612, in VE\n    new_factor = sum_out_variable(multiply_factors(bucket), var)\n  File "students//yesmukha/A4/bnetbase.py", line 362, in multiply_factors\n    value = value * f.get_value(n)\n  File "students//yesmukha/A4/bnetbase.py", line 227, in get_value\n    index = index * v.domain_size() + v.value_index(variable_values[0])\n  File "students//yesmukha/A4/bnetbase.py", line 68, in value_index\n    return self.dom.index(value)\nValueError: \'absent\' is not in list\n'
VE Test 5 ....
====================
Test Case: [function=ve_test_6]	[0/1]
	A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 193, in ve_test_6\n    probs = stu_solution.VE(Asia, Cancer, [])\n  File "students//yesmukha/A4/bnetbase.py", line 612, in VE\n    new_factor = sum_out_variable(multiply_factors(bucket), var)\n  File "students//yesmukha/A4/bnetbase.py", line 362, in multiply_factors\n    value = value * f.get_value(n)\n  File "students//yesmukha/A4/bnetbase.py", line 227, in get_value\n    index = index * v.domain_size() + v.value_index(variable_values[0])\n  File "students//yesmukha/A4/bnetbase.py", line 68, in value_index\n    return self.dom.index(value)\nValueError: \'absent\' is not in list\n'
VE Test 6 ....
ve_test_6: 
====================
Test Case: [function=ve_test_7]	[0/1]
	ve_test_7: 
VE Test 7 ....
A runtime error occurred: 'Traceback (most recent call last):\n  File "/Users/JaglalLab/Desktop/A4/autograder/auto_grader/student_grader/assignment/A4_tests.py", line 227, in ve_test_7\n    probs1 = stu_solution.VE(Asia, Smoking, [Dyspnea])\n  File "students//yesmukha/A4/bnetbase.py", line 601, in VE\n    Factors_1.append(restrict_factor(f, var, var.get_evidence()))\n  File "students//yesmukha/A4/bnetbase.py", line 423, in restrict_factor\n    Restrict.add_values(values)\n  File "students//yesmukha/A4/bnetbase.py", line 170, in add_values\n    index = index * v.domain_size() + v.value_index(t[0])\n  File "students//yesmukha/A4/bnetbase.py", line 68, in value_index\n    return self.dom.index(value)\nValueError: \'absent\' is not in list\n'